### ISSUE TITLE
override client_id in syslog messages

### ISSUE THREAD

**Issue by Marku555** [TheStaticTurtle/esphome_syslog#10]
Hello!
Is it possible to override client_id in syslog messages?
I see the `client_id` in source files, but when I try to set custom client_id, esphome dashbord show me error that `[client_id] is an invalid option for [syslog]. Please check the indentation.`

**Comment by TheStaticTurtle** [comment]
Hello,

The client_id is set from the `App.get_name()` esphome function, which is I'm not mistaken, takes the name you gave to your project with the following block:
```yaml
esphome:
  name: my-example-project
```
See: https://github.com/TheStaticTurtle/esphome_syslog/blob/main/syslog_component.cpp#L25

I would suggest that you change it here to maintain some coherence between the different parts of ESPhome

That being said, the only thing that would need modification is the `__init__.py` script in which I didn't add the `set_client_id` to the `to_code` function and the `client_id` to the `CONFIG_SCHEMA` schema.

**Comment by Marku555** [comment]
Thx, I added `client_id` to `CONFIG_SCHEMA` and `to_code` and now I have desired result.
I want to have short app name in `name` field and fqdn in client_id in syslog messages so I can simple filter them on the syslog server and write them to separate files for each device.

**Comment by TheStaticTurtle** [comment]
Haa ok, feel free to do a PR, 😄 
Can I close the issue?

**Comment by Marku555** [comment]
Yes )
