### ISSUE TITLE
Merging this into esphome?

### ISSUE THREAD

**Issue by DjordjeMandic** [TheStaticTurtle/esphome_syslog#19]
Are there any plans to add this component to esphome?

**Comment by TheStaticTurtle** [comment]
Hello,

See https://github.com/esphome/feature-requests/issues/223#issuecomment-491528490

Basically, it needs to be well tested and maintained, and I can't say that I had time to do that.
I think that, at least for now, it's best to keep it as a custom component.

**Comment by DjordjeMandic** [comment]
Just for info there is a pr open, might be worth taking a look at it esphome/esphome#8637

**Comment by clydebarrow** [comment]
> Just for info there is a pr open

Yeah, I did take inspiration from your component, so thanks for that.

**Comment by johntdyer** [comment]
FWIW it says this is merged ... .
